### ISSUE TITLE
On iOS Safari, the rear camera cannot be used

### ISSUE THREAD

**Issue by choyiny** [maxstrauch/ngx-zxing-multicode#1]
There is a dropdown for "Video Source 1" and "Video Source 2" but both leads to the rear camera. On ngx-scanner it properly shows the rear camera and front camera name. I'm on iOS 12.2.

I wonder if you have any suggestions what the problem might be.

**Comment by AE1NS** [comment]
This error does not depend to iOS. Its a general bug inside [ngx-zxing-multicode.component.html](https://github.com/maxstrauch/ngx-zxing-multicode/blob/master/projects/ngx-zxing-multicode/src/lib/ngx-zxing-multicode.component.html). The value of the select option is always [object Object], because the option gets the value **device** but not **device.deviceId**. In my case I just wanted to loop through the sources, so this is my solution:

- Get the reference to the qr scanner component inside your component:
`@ViewChild(NgxZxingMulticodeComponent) qrObject;`
- Add a custom button to the UI (absolute positioning)
- Add a listener to the button and select the next source by the deviceId:
```
const selectedDeviceIndex = this.qrObject.devices.indexOf(this.qrObject.selectedDevice);
this.qrObject.selectedDevice = this.qrObject.devices[(selectedDeviceIndex  + 1) % this.qrObject.devices.length];
this.qrObject.onDeviceSelected();
```

**Comment by maxstrauch** [comment]
Has been fixed just now
